// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using PFP;
//
//    var model = Model.FromJson(jsonString);

namespace PFP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class Model
    {
        public String IdEmpleado { get; set; }
        public String Contraseña { get; set; }
    }
    public partial class Respon
    {
        [JsonProperty("Response")]
        public string Response { get; set; }
        [JsonProperty("IdEmpresa")]
        public string IdEmpresa { get; set; }
    }
    public partial class DatosEmp
    {
        [JsonProperty("Nombre")]
        public string Nombre { get; set; }
        [JsonProperty("Empresa")]
        public string Empresa { get; set; }
        [JsonProperty("Ejes")]
        public int Ejes { get; set; }
        [JsonProperty("Tarifa")]
        public int Tarifa { get; set; }
        [JsonProperty("Estatus")]
        public string Estatus { get; set; }
    }
    public partial class TokenResp
    {
        [JsonProperty("TOKEN_ACTUAL")]
        public string TOKEN_ACTUAL { get; set; }
    }
    }