// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using StadiumFood;
//
//    var modelLogin = ModelLogin.FromJson(jsonString);

namespace StadiumFood.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ModelLogin
    {
        [JsonProperty("Nom_Usuario")]
        public string Nom_Usuario { get; set; }

        [JsonProperty("Contrasena")]
        public string Contrasena { get; set; }

        [JsonProperty("ubicacion")]
        public string Ubicacion { get; set; }
    }

    public partial class ModelLogin
    {
        public static ModelLogin FromJson(string json) => JsonConvert.DeserializeObject<ModelLogin>(json, StadiumFood.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ModelLogin self) => JsonConvert.SerializeObject(self, StadiumFood.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
