// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using StadiumFood;
//
//    var modelRegiter = ModelRegiter.FromJson(jsonString);

namespace StadiumFood
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ModelRegiter
    {
        [JsonProperty("Nom_Usuario")]
        public string NomUsuario { get; set; }

        [JsonProperty("Nom_Completo")]
        public string NomCompleto { get; set; }

        [JsonProperty("Correo_Electronico")]
        public string CorreoElectronico { get; set; }

        [JsonProperty("Num_Telefono")]
        public string NumTelefono { get; set; }

        [JsonProperty("Sexo")]
        public string Sexo { get; set; }

        [JsonProperty("Contrasena")]
        public string Contrasena { get; set; }

        [JsonProperty("idu_tipoususario")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IduTipoususario { get; set; }

        [JsonProperty("Fec_Nacimieto")]
        public DateTimeOffset FecNacimieto { get; set; }
    }

    public partial class ModelRegiter
    {
        public static ModelRegiter FromJson(string json) => JsonConvert.DeserializeObject<ModelRegiter>(json, StadiumFood.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ModelRegiter self) => JsonConvert.SerializeObject(self, StadiumFood.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
